### ISSUE TITLE
fabric8-auth fails on GKE

### ISSUE THREAD

**Issue by jstrachan** [fabric8-services/fabric8-auth#105]
```
{"err":"unable to load Keycloak public keys","level":"panic","msg":"failed to create token manager","pid":1,"time":"2017-09-15 09:57:06"}
panic: (*logrus.Entry) (0xa8e6e0,0xc420306eb0)

goroutine 1 [running]:
github.com/fabric8-services/fabric8-auth/vendor/github.com/Sirupsen/logrus.Entry.log(0xc42016db80, 0xc420139950, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x40e600, ...)
	/home/jenkins/go/src/github.com/fabric8-services/fabric8-auth/vendor/github.com/Sirupsen/logrus/entry.go:124 +0x340
github.com/fabric8-services/fabric8-auth/vendor/github.com/Sirupsen/logrus.(*Entry).Panic(0xc420306e60, 0xc42049fa18, 0x1, 0x1)
	/home/jenkins/go/src/github.com/fabric8-services/fabric8-auth/vendor/github.com/Sirupsen/logrus/entry.go:169 +0x11b
github.com/fabric8-services/fabric8-auth/vendor/github.com/Sirupsen/logrus.(*Entry).Panicln(0xc420306e60, 0xc42049fa90, 0x1, 0x1)
	/home/jenkins/go/src/github.com/fabric8-services/fabric8-auth/vendor/github.com/Sirupsen/logrus/entry.go:264 +0xe0
github.com/fabric8-services/fabric8-auth/log.Panic(0x0, 0x0, 0xc420139830, 0xabc05a, 0x1e, 0x0, 0x0, 0x0)
	/home/jenkins/go/src/github.com/fabric8-services/fabric8-auth/log/log.go:248 +0x24f
main.main()
	/home/jenkins/go/src/github.com/fabric8-services/fabric8-auth/main.go:144 +0x2275
```
not sure whats wrong; the keycloak URL looks valid: `https://keycloak.fabric8-js.test.fabric8.io`

I think this is actually caused by rate limiting on the kube-lego generation of the https certs though!

**Comment by jstrachan** [comment]
the workaround is to include `--http=true` on the `gofabric8 deploy` command

**Comment by gintautassulskus** [comment]
Any success running on k8s > 1.7?

I am having the same issue with Kubernetes 1.8. 
The provided workaround did not help: `gofabric8 deploy --http=true --package system -n fabric8`.
