### ISSUE TITLE
auth pod failing to start

### ISSUE THREAD

**Issue by mtbvang** [fabric8-services/fabric8-auth#479]
## Expected behavior

I'm installing fabric8 4.x with gofabric8 deploy command and it was working the last time I used it two weeks ago. Today the auth, init-tenant and fabric8 pods are all failing to start.

## Actual behavior

This seems to be the same issue #105 that has been closed. the --http=true flag did not fix the problem. The keycloak url https://keycloak.fabric8-js.test.fabric8.io mentioned in #105 returns 'default backend - 404'

Auth pod log:

`

{"err":"unable to load Keycloak public keys","level":"panic","msg":"failed to create token manager","pid":618,"time":"2018-05-02 08:40:44"}
--
  | panic: (*logrus.Entry) (0xb1e280,0xc420213680)
  |  
  | goroutine 1 [running]:
  | github.com/fabric8-services/fabric8-auth/vendor/github.com/sirupsen/logrus.Entry.log(0xc42001c550, 0xc420221c50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x40e600, ...)
  | /home/jenkins/go/src/github.com/fabric8-services/fabric8-auth/vendor/github.com/sirupsen/logrus/entry.go:124 +0x340
  | github.com/fabric8-services/fabric8-auth/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc420213630, 0xc42015f9c8, 0x1, 0x1)
  | /home/jenkins/go/src/github.com/fabric8-services/fabric8-auth/vendor/github.com/sirupsen/logrus/entry.go:169 +0x11b
  | github.com/fabric8-services/fabric8-auth/vendor/github.com/sirupsen/logrus.(*Entry).Panicln(0xc420213630, 0xc42015fa40, 0x1, 0x1)
  | /home/jenkins/go/src/github.com/fabric8-services/fabric8-auth/vendor/github.com/sirupsen/logrus/entry.go:264 +0xe0
  | github.com/fabric8-services/fabric8-auth/log.Panic(0x0, 0x0, 0xc420221bc0, 0xb4e979, 0x1e, 0x0, 0x0, 0x0)
  | /home/jenkins/go/src/github.com/fabric8-services/fabric8-auth/log/log.go:248 +0x24f
  | main.main()
  | /home/jenkins/go/src/github.com/fabric8-services/fabric8-auth/main.go:145 +0x24d0

`

## Steps to reproduce the problem

Install fabric8 using gofabric8:
gofabric8 deploy --version-console v4.0.208 --package system -n fabric8 --legacy false --github-client-id ${githubClientId} --github-client-secret ${githubSecret}

## Specifications

Installing fabric8 v4.0.208
CentOS Linux release 7.4.1708

**Comment by mtbvang** [comment]
I just recreated everything including my local openshift cluster and everything is starting up. The https://keycloak.fabric8-js.test.fabric8.io/ url still gives the 404 page so that wasn't the issue.
